### ISSUE TITLE
Save settings without checking choice causes flag icon disappearance

### ISSUE THREAD

**Issue by minivio** [KinoKabaret/Kinoit-Quasar-Skeleton#7]
- **Firefox, Safari, Chrome, Opera**: If you click on Language button, modal opens. If you click on "save settings" without any choice checked, the flag icon image disappears.
Tip: have current language pre-selected in modal.
![capture d ecran 2018-02-11 a 16 55 40](https://user-images.githubusercontent.com/23116123/36075243-6a9feca0-0f4c-11e8-993b-2147c7445f03.png)

**Comment by nothingismagick** [comment]
The problem wasn't just the logo, it was two things. The right place for the 'selected' flag in the DB was in the selectOptions. Just setting it for the default (English) worked to solve the pre-selection. Good to know. The issue you are referencing was in localeChange(Dialog.create({form.option.model ... 
I changed the model to use this.flag.selected to override any weirdness. 
Fixed in 0.2.2
